---
deployment:
  tasks:
    - export DEPLOY_DIR=/home/tbotsuz/public_html
    - git checkout -f main
    - composer install --no-dev --optimize-autoloader
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
