---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tbotsuz/public_html/
    - cp /home/tbotsuz/repositories/mirshood-invoice/.env $DEPLOYPATH
    - cp -R * $DEPLOYPATH
    - cd $DEPLOYPATH
    - composer install --no-dev --optimize-autoloader
    - php artisan key:generate
    - php artisan migrate --force
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache
    - chmod -R 775 storage bootstrap/cache

